# numpy practice session

In [1]:
import numpy as np

# Creating an array using numpy

In [2]:
food=np.array(["pakora","Samsoa", "Raita"])
food

array(['pakora', 'Samsoa', 'Raita'], dtype='<U6')

In [5]:
price= np.array([5,5,5])
price

array([5, 5, 5])

In [ ]:
numpy.ndarray

In [6]:
len(price)

3

In [7]:
price[2]

5

In [8]:
food[1]

'Samsoa'

In [9]:
price.mean()

5.0

In [10]:
# Zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#specify
np.arange (2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [16]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
# table
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [20]:
# line space
np.linspace(0,100, num=10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [21]:
# specify your data type
np.ones(50,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [25]:
#Array functions
a=np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [26]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [27]:
b=np.array([10.2,3.4,53.6,6,91.6,45.5])
b

array([10.2,  3.4, 53.6,  6. , 91.6, 45.5])

In [28]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,   6. ,  91.6,  45.5])

In [29]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,   6. ,  10. ,  10.2,  10.3,
        12. ,  15. ,  45.5,  53.6,  91.6, 100. , 320. ])

# Two dimensional (2D) Array

In [33]:
x= np.array([[1,2],[5,4]])
x

array([[1, 2],
       [5, 4]])

In [34]:
y=np.array([[6,7],[8,9]])
y

array([[6, 7],
       [8, 9]])

In [39]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])